In [15]:
print('welcome back')

welcome back


cddCS

cDc

In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [17]:
df=pd.read_csv('car-sales.csv')
df.head()

Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00

In [18]:
df.describe()

Odometer (KM)      Doors
count      10.000000  10.000000
mean    78601.400000   4.000000
std     61983.471735   0.471405
min     11179.000000   3.000000
25%     35836.250000   4.000000
50%     57369.000000   4.000000
75%     96384.500000   4.000000
max    213095.000000   5.000000

In [19]:
import numpy as np

# Datatype and Attributes

In [20]:
a1=np.array([[1,2,3],
           [3,4,5]])

In [21]:
a1

array([[1, 2, 3],
       [3, 4, 5]])

In [22]:
type(a1)

numpy.ndarray

In [23]:
a2=np.array([[[1,2,3],
             [2,3,4]],
            [[2,3,5],
             [3,4,5]]])
a2

array([[[1, 2, 3],
        [2, 3, 4]],

       [[2, 3, 5],
        [3, 4, 5]]])

In [24]:
a1.shape


(2, 3)

In [25]:
a2.shape

(2, 2, 3)

In [26]:
a1.ndim

2

In [27]:
a2.ndim

3

In [28]:
a1.size

6

In [29]:
a2.size

12

In [30]:
d=pd.DataFrame(a1)
d

0  1  2
0  1  2  3
1  3  4  5

In [31]:
ones=np.ones(4)#shift tab inside braces will give information about this
ones

array([1., 1., 1., 1.])

In [32]:
p=np.ones((2,3))
p

array([[1., 1., 1.],
       [1., 1., 1.]])

In [33]:
q=np.zeros((3,4))
q

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
range=np.arange(0,12,3)
range

array([0, 3, 6, 9])

In [35]:
random=np.random.randint(1,10,size=(4,5))#size here actually represents the shape. rows-4 & columns-5
random

array([[8, 7, 8, 7, 7],
       [9, 7, 2, 3, 7],
       [3, 1, 2, 9, 6],
       [7, 8, 2, 3, 5]])

In [36]:
random1=np.random.random((3,4))
random1

array([[0.05678326, 0.12364769, 0.80122245, 0.74925777],
       [0.17901202, 0.91355373, 0.04882816, 0.82615373],
       [0.32257617, 0.99905524, 0.35061925, 0.38446111]])

# Random Seed

In [37]:
np.random.seed()#genrates different random numbers each time we run it
np.random.seed(1)# generates same random numbers each time we run it
random2=np.random.random((3,5))
random2

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
        1.46755891e-01],
       [9.23385948e-02, 1.86260211e-01, 3.45560727e-01, 3.96767474e-01,
        5.38816734e-01],
       [4.19194514e-01, 6.85219500e-01, 2.04452250e-01, 8.78117436e-01,
        2.73875932e-02]])

# Viewing arrays and matrices

In [38]:
np.unique(3)

array([3])

In [39]:
np.unique(random)

array([1, 2, 3, 5, 6, 7, 8, 9])

# Manipulating and comparing arrays

In [40]:
a1=np.array([1,2,3])
a2=np.array([[1,2,3],[2,3.3,4.2]])
a1*a2# numpy multiplication is basically a matri multiplication(as simple as that)

array([[ 1. ,  4. ,  9. ],
       [ 2. ,  6.6, 12.6]])

In [41]:
a1/a2

array([[1.        , 1.        , 1.        ],
       [0.5       , 0.60606061, 0.71428571]])

In [42]:
a1%a2

array([[0., 0., 0.],
       [1., 2., 3.]])

In [43]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

In [44]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

# Attributes

In [45]:
lis=[1,2,3,4]
lis

[1, 2, 3, 4]

In [46]:
type(lis)

list

In [47]:
sum(lis)

10

In [48]:
import numpy as np
a1=np.array([1,2,3,4,5])
type(a1)

numpy.ndarray

In [49]:
large_array=np.random.random(1000000)
large_array.size

1000000

In [50]:
large_array[:1000]

array([6.70467510e-01, 4.17304802e-01, 5.58689828e-01, 1.40386939e-01,
       1.98101489e-01, 8.00744569e-01, 9.68261576e-01, 3.13424178e-01,
       6.92322616e-01, 8.76389152e-01, 8.94606664e-01, 8.50442114e-02,
       3.90547832e-02, 1.69830420e-01, 8.78142503e-01, 9.83468338e-02,
       4.21107625e-01, 9.57889530e-01, 5.33165285e-01, 6.91877114e-01,
       3.15515631e-01, 6.86500928e-01, 8.34625672e-01, 1.82882773e-02,
       7.50144315e-01, 9.88861089e-01, 7.48165654e-01, 2.80443992e-01,
       7.89279328e-01, 1.03226007e-01, 4.47893526e-01, 9.08595503e-01,
       2.93614148e-01, 2.87775339e-01, 1.30028572e-01, 1.93669579e-02,
       6.78835533e-01, 2.11628116e-01, 2.65546659e-01, 4.91573159e-01,
       5.33625451e-02, 5.74117605e-01, 1.46728575e-01, 5.89305537e-01,
       6.99758360e-01, 1.02334429e-01, 4.14055988e-01, 6.94400158e-01,
       4.14179270e-01, 4.99534589e-02, 5.35896406e-01, 6.63794645e-01,
       5.14889112e-01, 9.44594756e-01, 5.86555041e-01, 9.03401915e-01,
      

In [51]:
%timeit#used to calculate the time it took to execute a set of statements

UsageError: Line magic function `%timeit#used` not found.


In [ ]:
%timeit sum(large_array)
%timeit np.sum(large_array)

In [52]:
a2

array([[1. , 2. , 3. ],
       [2. , 3.3, 4.2]])

In [55]:
np.max(a2)

4.2

In [56]:
np.min(a2)

1.0

In [57]:
np.mean(a2)#mean

2.5833333333333335

In [58]:
np.std(a2)#standard deviation

1.0398984993204332

In [61]:
var=np.var(a2)
var

1.081388888888889

In [62]:
std=np.sqrt(var)
std

1.0398984993204332

# Reshape and Transpose

In [63]:
# we alwasys need to check the shape of the array and reshaping is a very useful topic there
a1.shape

(5,)

In [64]:
a2.shape

(2, 3)

In [69]:
random.shape

(4, 5)

In [70]:
random

array([[8, 7, 8, 7, 7],
       [9, 7, 2, 3, 7],
       [3, 1, 2, 9, 6],
       [7, 8, 2, 3, 5]])

In [76]:
r=random.reshape(2,2,5)#reshaping
r

array([[[8, 7, 8, 7, 7],
        [9, 7, 2, 3, 7]],

       [[3, 1, 2, 9, 6],
        [7, 8, 2, 3, 5]]])

In [78]:
r.T# transpose

array([[[8, 3],
        [9, 7]],

       [[7, 1],
        [7, 8]],

       [[8, 2],
        [2, 2]],

       [[7, 9],
        [3, 3]],

       [[7, 6],
        [7, 5]]])

In [79]:
r.T.shape

(5, 2, 2)

# Dot product

In [80]:
np.random.seed(0)
m1=np.random.randint(10,size=(4,5))
m2=np.random.randint(10,size=(4,5))

In [81]:
m1

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1],
       [6, 7, 7, 8, 1]])

In [82]:
m2

array([[5, 9, 8, 9, 4],
       [3, 0, 3, 5, 0],
       [2, 3, 8, 1, 3],
       [3, 3, 7, 0, 1]])

In [84]:
m1*m2#normal product( multiplication is done only for the same index numbers)

array([[25,  0, 24, 27, 28],
       [27,  0, 15, 10,  0],
       [14, 18, 64,  8,  3],
       [18, 21, 49,  0,  1]])

In [89]:
np.dot(m1,m2.T,out=None)#Dot product ( Matrix Multiplication)
# can be possible only if (a,b) * (b,n) ; b should be same

array([[104,  39,  58,  43],
       [146,  52,  81,  75],
       [229,  85, 107,  96],
       [225,  79, 100,  89]])

# Coparision Operators

In [97]:
a1=[1,2,3]
a1

[1, 2, 3]

In [91]:
a2

array([[1. , 2. , 3. ],
       [2. , 3.3, 4.2]])

In [99]:
o=a1>a2
o

array([[False, False, False],
       [False, False, False]])

In [100]:
type(o)

numpy.ndarray

In [101]:
o.dtype#datatype

dtype('bool')

# Sorting Arrays

In [102]:
random

array([[8, 7, 8, 7, 7],
       [9, 7, 2, 3, 7],
       [3, 1, 2, 9, 6],
       [7, 8, 2, 3, 5]])

In [105]:
np.sort(random)# Sorting the values

array([[7, 7, 7, 8, 8],
       [2, 3, 7, 7, 9],
       [1, 2, 3, 6, 9],
       [2, 3, 5, 7, 8]])

In [106]:
np.argsort(random)# Sorting the values and displaying only Indices

array([[1, 3, 4, 0, 2],
       [2, 3, 1, 4, 0],
       [1, 2, 0, 4, 3],
       [2, 3, 4, 0, 1]], dtype=int64)

In [107]:
np.argmax(random)

5

In [109]:
np.max(random)

9

In [110]:
np.min(random)

1

In [113]:
np.argmin(random)

11

# Turning images into Numpy arrays

<img src="numpy-images/panda.png"/>

In [120]:
#<img src="numpy-images/panda.png"/> (above picture in markdown)(img src- image source)

In [127]:
# turn an image into Numpy string
from matplotlib.image import imread #imread- image read
panda=imread('numpy-images/panda.png')

In [128]:
print(type(panda))

<class 'numpy.ndarray'>


In [129]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [130]:
panda.size,panda.shape,panda.ndim

(24465000, (2330, 3500, 3), 3)

<img src="numpy-images/car-photo.png"/>

In [131]:
car=imread("numpy-images/car-photo.png")

In [133]:
car.size,car.shape,car.ndim

(991300, (431, 575, 4), 3)

In [134]:
car

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]],

       [[0.44313726, 0.43529412, 0.40392157, 1.        ],
        [0.3137255 , 0.31764707, 0.27450982, 1.        ],
        [0.2       , 0.21176471, 0.14117648, 1.        ],
        ...,
        [0.5058824 , 0.5372549 , 0.4117647 , 1.        ],
        [0.49803922, 0.52156866, 0.39607844, 1.        ],
        [0.4       , 0.42745098, 0.34117648, 1.        ]],

       [[0.39607844, 0.38039216, 0.34117648, 1.        ],
        [0.31764707, 0.3137255 , 0.27450982, 1.        ],
        [0.28627452, 0.29411766, 0.24705882, 1.        ],
        ...,
        [0.44705883, 0.45882353, 0.32156864, 1.        ],
        [0.45882353, 0.482352